config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :inventories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @inventory = Inventory.all
  end

  def show
    @product = Inventory.find(params[:id])
  end

  def new
    @product = Inventory.new
  end

  def create
    @product = Inventory.new(product_params)
    if @product.save!
      redirect_to inventories_path
    else
      render :new
    end
  end

  private

  def product_params
    params.require(:inventory).permit(:name, :amount, :details, :supplier, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/inventories/index.html.erb
<h1>Your inventory app</h1>
<% @inventory.each do |article| %>
<%= link_to article.name, inventories_path(article) %> ||
<%= article.amount %><br/>
<% end %>

<%= link_to 'Add product', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>Your inventory app</h1>

<h2>Create a new product:</h2>

<%= form_with model: @product do |p| %>
  <%= p.label :name  %>
  <%= p.text_field :name  %>
  <%= p.label :amount  %>
  <%= p.text_field :amount  %>
  <%= p.label :details  %>
  <%= p.text_field :details  %>
  <%= p.label :supplier %>
  <%= p.text_field :supplier %>
  <%= p.label :price  %>
  <%= p.text_field :price  %>
  <%= p.submit %>
<% end %>

app/views/inventories/show.html.erb
<h1>Your inventory app</h1>

<%= @product.name %><br/>
<%= @product.amount %><br/>
<%= @product.details %><br/>
<%= @product.supplier %><br/>
<%= @product.price %><br/>

<%= link_to 'Back to Inventory', inventories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStoreInventory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>